version: '3'
services:
  szm-delivery-elastic:
    image: gcr.io/mawa-225208/szm-delivery-elastic:latest 
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - szm-delivery-elastic-data:/usr/share/elasticsearch/data
      - szm-delivery-elastic-log:/usr/share/elasticsearch/logs
      - szm-delivery-elastic-backup:/usr/share/elasticsearch/backup
    container_name: szm-delivery-elastic
    environment:
      - "discovery.type=single-node"
  szm-delivery:
    image: gcr.io/mawa-225208/szm-delivery:latest
    ports:
      - 8080:8080
    container_name: szm-delivery
    env_file:
      - delivery.env
  media-service:
    image: gcr.io/mawa-225208/media-service:latest
    ports:
      - 3500:3500
    container_name: media-service
    env_file:
      - media-service.env
volumes:
  szm-delivery-elastic-data:
    driver: local
  szm-delivery-elastic-log:
    driver: local
  szm-delivery-elastic-backup:
    driver: local

